### ISSUE TITLE
Difference with Harvey? Possible APE back-ports to "regular" Plan9 (9front)?

### ISSUE THREAD

**Issue by staalmannen** [JehanneOS/jehanne#10]
Hi

This looks like a very interesting OS project. There is also another GPL-licensed fork of Plan9 built with GCC : Harvey OS (https://harvey-os.org/). Are there any fundamental differences between the projects? Would they benefit from merger?

You got libposix and Harvey got apex (extended APE). I am especially interested in that you have gotten SIGCHILD to work so that mksh can work well (I would love to see the old pdksh replaced with mksh in regular ape on 9front). Any chance of "upstreaming"/"backporting" this posix compat to 9front or 9legacy?

**Comment by Shamar** [comment]
Hi staalmannen, thanks for your questions.

I worked as a core contributor to Harvey for half 2015 but it turned out we had different visions about how a distributed operating system should work and they asked me to fork the project to pursuit my own interests.

Sadly they later removed my Copyright statements and my name from the project without removing my contributions (actually violating the GPL license in a way that would terminate their rights) and [when I noticed it and asked to restore them](https://github.com/Harvey-OS/harvey/issues/698) (to protect Jehanne where I reused most of my patches) they `git rebase`d their main repo to remove me from their history (but some of my changes somehow found their path to their code base in the process, "accidentally" squashed together with other large commits).

So the first difference is that [Jehanne is Free Software while Harvey is Open Source](https://medium.com/@giacomo_59737/what-i-wish-i-knew-before-contributing-to-open-source-dd63acd20696).

Also we have different visions about the design of distributed operating systems. 

Jehanne is a pursuit for simplicity.  
I'm happy to trade compatibility for simplicity. They are not.  
Also I rewrote/removed large parts of the kernel to this aim.

> Would they benefit from merger?

I don't think so: we are technically and culturally incompatible.  
I would say that, as long as they respect the licenses of my code, they can do whatever they want with it, but they didn't respected the license before so... I really would hate to see (more of) my code in Harvey again.

As for libposix vs APE/APEX they are pretty different beasts.
LibPOSIX is a POSIX system facade to Jehanne's kernel and libc: it's not a C standard library, just the glue required by a real one (like newlib or musl) to use the system.  
LibPOSIX however use some of the peculiarities of Jehanne.
I would have no objection to a port of libposix to 9front or 9legacy, but it's not a trivial task for several reasons. Also the license of some pieces are not compatible so I should do the port myself to avoid the potential of copyright issues like Harvey's one.

Finally, 9front is way ahead of Jehanne (and basically everybody else) in term of features and stability.  
Jehanne is just a research project.
