### ISSUE TITLE
package management: hermes?

### ISSUE THREAD

**Issue by akavel** [JehanneOS/jehanne#16]
Hi! I stumbled upon this repo via lobste.rs. I noticed you ponder package management in the last post; I'm curious if https://github.com/andrewchambers/hermes might be interesting to you?

**Comment by 0xtrzy** [comment]
In my opinion brew are better and more flexible.
I see a simple filesystem for package. It is fastest ever packagemenager but is still in alpha

**Comment by Shamar** [comment]
Hi @akavel, it has been a while [since I was banned by Lobste.rs](https://dev.to/shamar/i-have-been-banned-from-lobsters-ask-me-anything-5041)!

Happy to see someone is still interested in Jehanne there! I remember well when I proposed to add the osdev tag, but things changes. Would you mind to share a link to the thread where you read about Jehanne?

Anyway, @andrewchambers' Hermes looks very cool and quite aligned with Jehanne philosophy of simplicity and minimalism, but for the core system (where a paclage manager belongs, to install non core components) I'd like to have something way smaller, that does not depend on something like Janet.

The most likely choice will be a bunch of script in rc.
I might consider something in lua or chibi-scheme though.

**Comment by Shamar** [comment]
@0xtrzy mind to share a link? 

Or maybe you really mean https://brew.sh ?

**Comment by andrewchambers** [comment]
I noticed this popped up on my feed, I am working on a newer simpler/smaller package manager actually, I would say not to use hermes for this.

> I might consider something in lua or chibi-scheme though.
Lua and Janet really are in the same size class.

**Comment by akavel** [comment]
@Shamar it would appear to be this one: https://lobste.rs/s/vdgemd/jehanne_simple_operating_system

@andrewchambers I'd really love to hear about it whenever you decide to publish something! I'm personally especially interested in something that could (be made to by an interested third-party) support Windows, but I sure understand if you'd not care, and I'm really interested in the topic regardless and anyway. NixOS whetted my appetite, and I'm a sucker for minimalism.

**Comment by Shamar** [comment]
Hi, [I'm moving Jehanne from GitHub](http://jehanne.h--k.it/2022/01/06/jehanne_is_moving.html), so I'm going to close all issues here.

The new repository is at https://gitea.it/JehanneOS/jehanne 

Hope you'll follow Jehanne there!
