### ISSUE TITLE
The build instructions are incomplete anyway... no kernel?!

### ISSUE THREAD

**Issue by dertuxmalwieder** [JehanneOS/jehanne#8]
git clone --recurse-subdirectories https://github.com/JehanneOS/jehanne
    cd jehanne
    ./hacking/devshell.sh
    ./hacking/continuous-build.sh

After a while: DONE. Now:

    ./hacking/runOver9P.sh 

Does not work as expected:

    Simulating Os User: &ninep.osUser{User:(*user.User)(0xc420062140), uid:1000, gid:1000}
    ./hacking/runOver9P.sh: line 54: cd: /home/tux/jehanne/arch/amd64/kern/: No such file or directory
    qemu-system-x86_64 -s -cpu Haswell -smp 4 -m 2048 -rtc clock=vm -no-reboot -serial mon:stdio --machine pc -netdev user,id=ethernet.0,hostfwd=tcp::5555-:1522,hostfwd=tcp::9999-:9,hostfwd=tcp::17010-:17010,hostfwd=tcp::17013-:17013 -device rtl8139,netdev=ethernet.0 -append "maxcores=1024 nvram=/boot/nvram nvrlen=512 nvroff=0 console=0 qemu-user=tux *acpi= nobootprompt=tcp fs=10.0.2.2 auth=10.0.2.2 " -initrd ./initrd -kernel jehanne.32bit
    warning: TCG doesn't support requested feature: CPUID.01H:ECX.fma [bit 12]
    warning: TCG doesn't support requested feature: CPUID.01H:ECX.fma [bit 12]
    warning: TCG doesn't support requested feature: CPUID.01H:ECX.fma [bit 12]
    (... snipped ...)
    qemu: could not load kernel 'jehanne.32bit': No such file or directory
    ./hacking/runOver9P.sh: line 78:    18 Terminated              $JEHANNE/hacking/bin/ufs -root=$JEHANNE

Why?

**Comment by szhilkin** [comment]
Try to run several time :)

**Comment by dertuxmalwieder** [comment]
How many times?

**Comment by Shamar** [comment]
Hi, sorry for the delay. Really.

This is a bit strange. What's your operating system?

Apparently, your build did not work.

Can you please share a log of these commands executed in the Jehanne root dir?

```
$ ./hacking/devshell.sh
JehanneDEV $ git clean -xfd
JehanneDEV $ build
```

**Comment by dertuxmalwieder** [comment]
It was Debian on WSL over Windows 10 Home. Currently:

    $ uname -a
    Linux LAPTOP-E7OHISR4 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 GNU/Linux

Retrying:

    $ ./hacking/devshell.sh
    JehanneDEV $ git clean -xfd
    Removing arch/amd64/include/syscalls.h
    JehanneDEV $ build
 
[Here's the log.](https://github.com/JehanneOS/jehanne/files/2448215/foo.txt) Looks OK - up to this point. Trying to run `runOver9P.sh` gives me a different error message now:

    Could not initialize SDL(No available video device) - exiting
    ./hacking/runOver9P.sh: line 78: 23623 Terminated              $JEHANNE/hacking/bin/ufs -root=$JEHANNE  (wd: ~/jehanne)

Progress, I guess?

**Comment by Shamar** [comment]
Yes.

It looks like qemu is having issues to draw your screen.  
I've never used WSL and I do not have a Windows machine available now.

Maybe [this](https://virtualizationreview.com/articles/2017/02/08/graphical-programs-on-windows-subsystem-on-linux.aspx) could help?

**Comment by dertuxmalwieder** [comment]
Ouch! I had Xming anyway (`deadpixi/sam` is my main notes editor at work - also on Windows 10), but it was not running. I should go to sleep... here we go!

![Screen](https://i.imgur.com/AzAoBRF.png)

Not sure whether to close this now - the main error seems to have dissolved on its own.

**Comment by Shamar** [comment]
Ok, let's close this issue with a bounty. :-)

Here how to start rio where you can play with sam, acme, [vt and mksh](http://jehanne.io/2018/01/06/jehanne-in-2017.html) on Jehanne:

```
bind -a '#m' /dev
hmi/mouse ps2
ms &
hmi/realemu
hmi/vga -m vesa -l 1024x768x8
rio -i /lib/riostart
```

You can also run the "quality assurance" tests in Jehanne (both in terminal and in rio) with

```
/qa/check
```

(but it will take a while)

Hope this helps!

**Comment by dertuxmalwieder** [comment]
Thank you!

**Comment by Shamar** [comment]
You are welcome! :-D

I have to confess that I'd like to port the improvements of https://github.com/deadpixi/sam to Jehanne's sam.

However I'm not sure about the licensing since the Jehanne's code is taken from https://github.com/brho/plan9 (thus it's GPLv2) while deadpixi's one is released as Lucent.

But something I would really appreciate would be a video tutorial for sam.  
Something like the Russ Cox's [A Tour of the Acme Editor](https://www.youtube.com/watch?v=dP1xVpMPn8M).

If you can record and share something like that (either in Jehanne, in Linux or in Windows), I would love to give it a look! I cannot get my head through the sam UI. Its workflow looks... strange.  
I guess I'm doing something wrong but I cannot say what.

**Comment by dertuxmalwieder** [comment]
I hate my voice (and my accent)... but I'll keep it in mind. Maybe I'll just do some annotations. ;-)

Isn't the GPL compatible with the Lucent license?

**Comment by Shamar** [comment]
I do not think anybody would care about your voice or accent.  
The audience will be mostly nerds, after all!
If you use [QEMU's VNC facilities](https://virtuallyfun.com/wordpress/2011/04/27/recording-qemus-vnc-output-to-a-flash-file/) with Jehanne drop me a line and I will link it from it's site.  
Just please, if you are going to put it on YouTube, [set its license as CC BY](https://www.youtube.com/watch?time_continue=35&v=3CrrbuCiTd0) so that it can be used in schools.  
Or maybe [join PeerTube](https://joinpeertube.org/en/)! ;-)

GPL and Lucent license are [not compatible](https://www.gnu.org/licenses/license-list.html#lucent102).   
You can use Lucent programs on Jehanne, but you cannot mix their code with other released under GPL.  
I can use 9front's code (with proper attribution) because they release their changes as MIT.

**Comment by dertuxmalwieder** [comment]
I got a half version done on Windows (over `plan9port` because I really prefer the deadpixi version) only to find that I'm definitely too unorganized for a video that is not totally confusing. I could make a PDF tutorial with screenshots, but Rob Pike has already done that in the 80s...

Sigh.
